# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-17 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydict',
            options={'verbose_name': '\u57ce\u5e02', 'verbose_name_plural': '\u57ce\u5e02'},
        ),
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '\u8bfe\u7a0b\u673a\u6784', 'verbose_name_plural': '\u8bfe\u7a0b\u673a\u6784'},
        ),
        migrations.AddField(
            model_name='courseorg',
            name='catgory',
            field=models.CharField(choices=[('pxjg', '\u57f9\u8bad\u673a\u6784'), ('gx', '\u9ad8\u6821'), ('gr', '\u4e2a\u4eba')], default='pxjg', max_length=20, verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='citydict',
            name='desc',
            field=models.CharField(max_length=30, verbose_name='\u57ce\u5e02\u63cf\u8ff0'),
        ),
    ]
