# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-22 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='(\u5206\u949f)'),
        ),
    ]
